USE ROLE ACCOUNTADMIN;

-- =====================================================
-- DEV
-- =====================================================
CREATE WAREHOUSE IF NOT EXISTS DBT_DEV_WH
    WAREHOUSE_SIZE = 'XSMALL';

CREATE DATABASE IF NOT EXISTS DBT_DEV_DB;

CREATE ROLE IF NOT EXISTS DBT_DEV_ROLE;

GRANT USAGE ON WAREHOUSE DBT_DEV_WH TO ROLE DBT_DEV_ROLE;
GRANT ALL ON DATABASE DBT_DEV_DB TO ROLE DBT_DEV_ROLE;

CREATE SCHEMA IF NOT EXISTS DBT_DEV_DB.DBT_SCHEMA;

-- =====================================================
-- UAT
-- =====================================================
CREATE WAREHOUSE IF NOT EXISTS DBT_UAT_WH
    WAREHOUSE_SIZE = 'XSMALL';

CREATE DATABASE IF NOT EXISTS DBT_UAT_DB;

CREATE ROLE IF NOT EXISTS DBT_UAT_ROLE;

GRANT USAGE ON WAREHOUSE DBT_UAT_WH TO ROLE DBT_UAT_ROLE;
GRANT ALL ON DATABASE DBT_UAT_DB TO ROLE DBT_UAT_ROLE;

CREATE SCHEMA IF NOT EXISTS DBT_UAT_DB.DBT_SCHEMA;

-- =====================================================
-- PROD
-- =====================================================
CREATE WAREHOUSE IF NOT EXISTS DBT_PRD_WH
    WAREHOUSE_SIZE = 'SMALL';

CREATE DATABASE IF NOT EXISTS DBT_PRD_DB;

CREATE ROLE IF NOT EXISTS DBT_PRD_ROLE;

GRANT USAGE ON WAREHOUSE DBT_PRD_WH TO ROLE DBT_PRD_ROLE;
GRANT ALL ON DATABASE DBT_PRD_DB TO ROLE DBT_PRD_ROLE;

CREATE SCHEMA IF NOT EXISTS DBT_PRD_DB.DBT_SCHEMA;

-- =====================================================
-- USER ACCESS
-- =====================================================
GRANT ROLE DBT_DEV_ROLE TO USER LXLOGICINC;
GRANT ROLE DBT_UAT_ROLE TO USER LXLOGICINC;
GRANT ROLE DBT_PRD_ROLE TO USER LXLOGICINC;